<?php

use App\Http\Controllers\GeminiController;
use Illuminate\Support\Facades\Route;

Route::get('/', [GeminiController::class, 'store']);



$flattenedCategories = [
    'Valentine\'s Gifts for Him',
    'Valentine\'s Gifts for Her',
    'Couple\'s Valentine Packages',
    'Vacation in Athens',
    'Vacation in Santorini',
    'Wellness Retreats',
    'Vacation in Crete',
    'Seaside Getaways',
    'Luxury SPA Resorts',
    'Lakeside Escapes',
    'Vacation in Rhodes',
    'City Breaks in Thessaloniki',
    'Workation Packages',
    'Vacation in Corfu',
    'Solo Retreats',
    'Romantic Getaways for Two',
    'Historical Castle Stays',
    'Couples SPA Packages',
    'Facial Treatments',
    'Relaxation Massages',
    'Men\'s Therapies',
    'Lymphatic Drainage',
    'Traditional Greek Therapies',
    'Ayurvedic Massages',
    'Prenatal Massages',
    'Medical Massages',
    'Full-Body Treatments',
    'SPA Rituals',
    'Back & Neck Massages',
    'Scalp Treatments',
    'Massage Bundles',
    'Fine Dining Experiences',
    'Greek Food Tastings',
    'Cooking Classes',
    'Gourmet Home Delivery',
    'Wine & Olive Oil Tastings',
    'Restaurant Vouchers',
    'Artisan Desserts',
    'International Cuisine Nights',
    'Brunch Specials',
    'Hot Air Balloon Rides',
    'Skydiving',
    'Paragliding',
    'Gliding Flights',
    'Scenic Helicopter Tours',
    'Flight Lessons',
    'Cinema Nights',
    'Online Workshops',
    'Cultural Tours',
    'Art & Craft Classes',
    'Photoshoot Sessions',
    'Perfume Crafting',
    'Theater & Concerts',
    'Museum Passes',
    'Dance/Music Lessons',
    'Bookstore Gift Cards',
    'Online Shopping Vouchers',
    'Magazine Subscriptions',
    'Go-Karting',
    'Drifting Experiences',
    'Driving Lessons',
    'ATV Adventures',
    'Tank Rides',
    'Monster Truck Rallies',
    'Motorcycle Tours',
    'Quad Biking',
    'Jeep Safaris',
    'Bike & Scooter Rentals',
    'Supercar Test Drives',
    'Convertible Cruises',
    'Custom Packages',
    'Escape Rooms',
    'Bowling',
    'Shooting Ranges',
    'Rock Climbing',
    'Horseback Riding',
    'Martial Arts Sessions',
    'Theme Park Tickets',
    'Paintball',
    'Laser Tag',
    'Golf Packages',
    'Board Game Cafés',
    'Hiking Trips',
    'VR Experiences',
    'Porsche Rides',
    'Lamborghini Drives',
    'Ferrari Tours',
    'Tesla Experiences',
    'Water Parks',
    'Pool & Sauna Access',
    'Fishing Trips',
    'Scuba Diving',
    'Sailing & Yacht Charters',
    'Flyboarding',
    'Jet Skiing',
    'Water Trampolines',
    'Kayaking',
    'Paddleboarding',
    'Surfing Lessons',
    'Boat & Water Bike Rentals',
    'Other Water Activities',
    'Skincare Treatments',
    'Beauty Packages',
    'Manicure & Pedicure',
    'Men\'s Grooming',
    'Health Checkups',
    'Professional Makeup',
    'Hair Treatments',
    'Body Sculpting',
    'Beauty Workshops',
    'Teeth Whitening',
    'Vacation in Italy',
    'Vacation in Turkey',
    'Vacation in Cyprus',
    'Other Destinations',
    'Blood Tests',
    'Dental Care',
    'Detox Programs',
    'Float Therapy',
    'Yoga & Meditation Retreats',
    'Holistic Therapies',
];
